### PR TITLE
add cubehelm function and route

### PR DESCRIPTION
**Pull request by MAH1987**
I added a function to Display the cube with the helmet overlay. 

when you like it, you can merge it :)

### CODE REVIEW

**Comment by LukeHandle** [comment]
Hey @MAH1987. Before we can merge this, it'll be a case of fixing and merging the #189.

I appreciate the work, but will be a little while before it sees primetime. (not sure when I will be re-visiting the refactor as Minotar is no longer on fire)

**Comment by LukeHandle** [comment]
@MAH1987 this is actually (a few years later :stuck_out_tongue_winking_eye:) now live! (...a merge into repo will follow at some point, but `version4` is the branch)

A kind of minor point, but I'm not sure if it should stay at "cubehelm/" or follow the "armor/cube" naming scheme we use with body/bust. I feel like the latter, but it's currently at `https://minotar.net/cubehelm/5c115ca73efd41178213a0aff8ef11e0`.

_though, it will likely move, so don't consider this "usable" and merged and docs updated_

**Comment by MAH1987** [comment]
Your welcome @LukeHandle, i use it for "years" :)
Happy to see, this project is still alive!

**Comment by LukeHandle** [comment]
This finally made it into master. I've raised #216 to track official release etc.

**Pull request closed without merging**
