### PR TITLE
Add CORS headers to endpoint responses

### PR DESCRIPTION
**Pull request by connor4312**
This adds CORS headers to all endpoint responses, resolving #167

### CODE REVIEW

**Comment by connor4312** [comment]
Wercker failed, but not because of changes in this PR... builds and runs successfully 

```
http get localhost:8000/skin/connor4312
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Content-Type, Content-Length, Accept-Encoding
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Content-Type: image/png
Date: Fri, 25 Sep 2015 12:54:59 GMT
Transfer-Encoding: chunked
X-Requested: skin
X-Result: ok



+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+
```

**Comment by LukeHandle** [comment]
I'm now away for a few days, but feel free to merge ahead of 2.8 as this has no config changes. I'm almost ready with new ansible stack to deploy all.

**Comment by clone1018** [comment]
I'm rebuilding now, I tried to move us to Werckers docker based builds but it failed.

**Comment by clone1018** [comment]
Is there not a way to modify the router at an early stage to always include the cors headers?

**Comment by LukeHandle** [comment]
I could also add it to Varnish as well

**Comment by connor4312** [comment]
> Is there not a way to modify the router at an early stage to always include the cors headers?

As far as I can see from the docs, no. The best (?) way to do this is to have a hierarchal routing system and be able to apply middleware and other options to subtrees. Gorilla doesn't seem to do this. Others might. If not it'd be an interesting exercise to build one.

**Comment by LukeHandle** [comment]
I've run this by @clone1018 on IRC, going to add this tomorrow (ish?) in Release-2.9:

````
func startServer(listen string) {
	r := Router{Mux: mux.NewRouter()}
	r.Bind()
	http.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET")
		w.Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding")
		r.Mux.ServeHTTP(w, req)
	})
	log.Printf("Starting on %s", listen)
	err := http.ListenAndServe(listen, nil)
	if err != nil {
		log.Fatal("ListenAndServe: \"%s\"", err.Error())
		os.Exit(1)
	}
}
````

Slightly neater we think, though still open for improvement:

01:37:53 <clone1018> Yeah it's better
01:38:05 <clone1018> I meant I think there would be a better way
01:38:08 <clone1018> Not that I knew of one

Does this trigger any better ideas @connor4312

**Comment by LukeHandle** [comment]
I have taken from this and created the release-2.9.1 PR #170 

Any thoughts?

**Comment by connor4312** [comment]
It seems like a mildly hackish way to go about it, but it works. Really the "solution" would be a fancier routing system, which we don't necessarily need (at this point)

**Pull request merged**
